#972 TProcessHelper, TSignalsDispatcher, and related classes & functions
pradosoft/prado pull request #986
Opened 2023-07-24 19:36 UTC by belisoful

- TProcessHelper for process related functions like forking (pcntl_fork) and isSystemWindows().
- TSignalsDispatcher for raising signal related global events from signals for multiple handlers per signal, alarm and disarm callbacks at a specific time (1 second precision), and for callbacks per child processes (proc_open, pcntl_fork, etc) when they end (or "stop and start"?).
- ISingleton is a new interface for application singleton objects
- TShellWriter is updated to use the TProcessHelper::isSystemWindows function -TComponent only hasMethod of global event handlers that do actually exist.  As a global event it exists always, but not the method.
- TEventSubscription example is updated to reflect TSignalsDispatcher and TSignalParameter
- TApplicationSignals behavior for configuration and attaching of TSignalsDispatcher
- TCaptureForkLog behavior for capturing the logs of forked child processes in the main log.  Effectively a ForkLogRouter but registering as a behavior on TApplication.
- TForkable behavior for attaching the owner's ::fxPrepareForFork() and ::fxRestoreAfterFork() handlers to their respective global events. -TGlobalClassAware behavior for attaching the owner's ::fxAttachClassBehavior() and ::fxDetachClassBehavior() to their respective global events so they change with global class changes without listening.
- TProcessWindowsPriority specifies the numeric priorities that windows uses for each respective priority level.
- TProcessWindowsPriorityName specifies the text priorities that windows uses for each respective priority level.

2023-07-25 11:44 UTC, belisoful commented
This took a while to ensure proper function and consideration.  This is ready for review and merge.

2023-07-31 20:39 UTC, ctrlaltca requested changes
Sorry for the delay, the PR looks fine with the exception of a couple of typos.

2023-07-31 20:39 UTC, ctrlaltca commented on framework/classes.php
> +'Forkable' => 'Prado\Util\Behaviors\Forkable',
Typo: TForkable

2023-07-31 20:39 UTC, ctrlaltca commented on framework/classes.php
> +'TSignalsParameter' => 'Prado\Util\TSignalsParameter',
Typo: TSignalParameter

2023-08-01 03:53 UTC, belisoful commented
No issue with the delay.  It's given me a little break that I needed.  I'll get on those typos asap

2023-08-01 06:16 UTC, belisoful commented
TSignalsParameter was the first pass name of the object.  further revision made is singular and the class file didn't get updated.  good catch.

2023-08-01 07:19 UTC, merged